### ISSUE TITLE
What's our project going to be?

### ISSUE THREAD

**Issue by franchyze923** [Qwertyismypw/Qwertyismypw.github.io#1]
Is our collab project going to be a website? If so I say we build a website that allows users to perform geospatial functions (Add points to database, buffer, clip etc). We can use python on the backend. We've talked about this before I think. It would involve a little bit of a lot of stuff.

Or we could just work together to build a geospatial python program. This might be simpler since it would just be code, no databases or servers or anything else. It would all just be on github. Might be good to start with. 

However I don't have an arc license at the moment so my contributions would need to use GDAL.

**Comment by Qwertyismypw** [comment]
I was thinking just a website to start out with that had paths to different pages depending on the aspect of projects (i.e attribution, spatial, database, etc). I would like to work on implementing JS buttons that run python on the backend, but I think we should build up to that.

I uninstalled arc, so we could use GDAL. If you would prefer to use Arc, I think I have a few licenses we could use.

**Comment by franchyze923** [comment]
ok, so I'm imagining a website where you drag in or browse to a shapefile, hit enter then it does some function like count the number of features and then returns that info.

**Comment by Qwertyismypw** [comment]
That could be a page that index directs to. I think that is a good idea. Do we have the data stored on github in like a json? or do they supply it and draw an aoi or supply the aoi?

**Comment by franchyze923** [comment]
They would supply their own shapefile. So the simplest thing would just be to count number of features in that shapefile. Once we successfully do that we can work on other functionality.

**Comment by Qwertyismypw** [comment]
Yea, I agree. I'll get started on that once I get that sweet table you implemented to some other stuff.
