### ISSUE TITLE
Getting HTML to display

### ISSUE THREAD

**Issue by Qwertyismypw** [Qwertyismypw/Qwertyismypw.github.io#2]
I am not sure how to get github to display our code in a new window. If you have any ideas, feel free to implement them if you can or tell me how. In the meantime, I am looking into it.

I am not sure if it is a setting, a privilege, or a structure issue (or something else).

**Comment by franchyze923** [comment]
What I did was clone the entire project, so then its installed on your local computer. I view and edit the code that way. Then when I want to push, I just sync it and it uploads to github. 

Is that what you were asking?

**Comment by Qwertyismypw** [comment]
I mean to have github display our html code in a new window. Currently, I am writing it in notepad ++ and displaying it that way, but I know there is a way to display it through github. I think you just have to set github up a certain way.

**Comment by franchyze923** [comment]
ohh ok, yea I think I remember you showing me your school stuff via github. But yea, I'm doing it the same way now. Working on it in notepad ++ then running it from there.
