### ISSUE TITLE
Updating Files

### ISSUE THREAD

**Issue by Qwertyismypw** [Qwertyismypw/Qwertyismypw.github.io#4]
Do you know how to update files in github without deleting them and re-uploading them? My current method is to do that and I feel like the point of github is to have versioning.

**Comment by franchyze923** [comment]
I believe it saves a copy still. Are you using the github desktop app? There is a history tab which shows older versions and gives you an option to revert.

**Comment by Qwertyismypw** [comment]
I am not using the desktop app. Is it required to use the app in order to reach that functionality? 

    On Monday, December 5, 2016 6:38 AM, Fran P. <notifications@github.com> wrote:
 

 I believe it saves a copy still. Are you using the github desktop app? There is a history tab which shows older versions and gives you an option to revert.—

**Comment by franchyze923** [comment]
Yes, I'm pretty sure you need either git or the github desktop app (which is basically just a gui for git). The program git is what actually tracks file changes. Github from my understanding is just a way to share and collaborate, not a version tracker. 

https://www.youtube.com/watch?v=cEGIFZDyszA

So what I did in the past was install git on my computer, not github. Then use git bash which is a shell for git, to basically initiate a folder as a project folder so then that folder now gets tracked and managed by git. Then you can push it to github. It's a lot easier with the github desktop app though and it does the same thing.
